# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_auto_20180606_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestpage',
            name='read_next',
            field=models.ForeignKey(blank=True, default=home.models.get_previous_digest_page, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.DigestPage'),
        ),
        migrations.AlterField(
            model_name='pressreleasepage',
            name='read_next',
            field=models.ForeignKey(blank=True, default=home.models.get_previous_press_release_page, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.PressReleasePage'),
        ),
        migrations.AlterField(
            model_name='recordpage',
            name='read_next',
            field=models.ForeignKey(blank=True, default=home.models.get_previous_record_page, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.RecordPage'),
        ),
        migrations.AlterField(
            model_name='tipsfortreasurerspage',
            name='read_next',
            field=models.ForeignKey(blank=True, default=home.models.get_previous_tips_page, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.TipsForTreasurersPage'),
        ),
    ]
